version: 1.0.0
description: 'The Swagger UI app renders a documentation based on the OpenAPI specification.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/swagger-ui.png'
website: 'https://github.com/apioo/fusio-apps-swaggerui'
downloadUrl: 'https://github.com/apioo/fusio-apps-swaggerui/archive/v1.0.0.zip'
sha1Hash: ad33b82c16d6e16f30e1ea3bac8c63fa86b6a31b
